In [1]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/cleaned_grievances.csv"
)

df.head()

,complaint,department,sentiment,cleaned_text
0,Water supply not available for 3 days,Water,Critical,water supply available day
1,Street light not working,Roads,Negative,street light work
2,Power outage in sector 10,Electricity,Critical,power outage sector
3,Garbage not collected for a week,Sanitation,Negative,garbage collect week
4,Water leakage near main road,Water,Negative,water leakage near main road

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(
    df["cleaned_text"]
)

y = df["department"]

print(X.shape)

(10, 30)

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [4]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=1000
)

lr_model.fit(
    X_train,
    y_train
)

lr_accuracy = lr_model.score(
    X_test,
    y_test
)

print(
    "Logistic Regression:",
    lr_accuracy
)

Logistic Regression: 0.5

In [5]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    random_state=42
)

rf_model.fit(
    X_train,
    y_train
)

rf_accuracy = rf_model.score(
    X_test,
    y_test
)

print(
    "Random Forest:",
    rf_accuracy
)

Random Forest: 0.5

In [6]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC()

svm_model.fit(
    X_train,
    y_train
)

svm_accuracy = svm_model.score(
    X_test,
    y_test
)

print(
    "SVM:",
    svm_accuracy
)

SVM: 0.5

In [9]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    svm_model,
    X,
    y,
    cv=2
)

print(
    "CV Score:",
    scores.mean()
)

CV Score: 0.4

In [10]:
comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "SVM"
    ],
    "Accuracy": [
        lr_accuracy,
        rf_accuracy,
        svm_accuracy
    ]
})

comparison

                 Model  Accuracy
0  Logistic Regression       0.5
1        Random Forest       0.5
2                  SVM       0.5

In [12]:
comparison.to_csv(
    "../reports/model_comparison.csv",
    index=False
)

print("Saved")

Saved

In [13]:
import joblib

joblib.dump(
    svm_model,
    "../models/department_classifier.pkl"
)

joblib.dump(
    vectorizer,
    "../models/tfidf_vectorizer.pkl"
)

print("Model Saved")

Model Saved